targets:
  $default:
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: stellerlink|lib/services/graphql/schema/schema.graphql
          output_dir: '../generated'
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: stellerlink|lib/services/graphql/schema/schema.graphql
          output_dir: '../generated'
